#################################### Solve CodeForces Problem Link :https://codeforces.com/problemset/problem/158/A ########################
#################################### Code Generated By: https://github.com/shahed-shd #######################################################
from sys import stdin, stdout
inp = [int(x) for x in stdin.read().split()]
n = inp.pop(0)
k = inp.pop(0)
k_th = inp[k-1]
cnt = 0
for x in inp:
	if x and x >= k_th:
		cnt += 1;

stdout.write(str(cnt) + '\n')
