#################################Solve CodeForces Problem Link:https://codeforces.com/problemset/problem/231/A #########################
#################################Code Generated By : Hasan Saleh ######################################
n=int(input()) 
c=0
for h in range(0,n):
    a=input() 
    if(a.count('1') >= 2):
        c+=1
print(c)
