###################################Solve CodeForces Problem BitLand++ Programming Language Link:https://codeforces.com/problemset/problem/282/A ##############
###################################Code Generated By Hasan Saleh ###########################++#################### 
n=int(input())
x=0 
for i in range(0,n):
    a=input()
    if(a.upper() == "++X" or a.upper() == "X++"):
        x=x+1
        pass
    elif(a.upper() == "--X" or a.upper() == "X--"):
        x=x-1
        pass
print(x) 
