#############################Solve CodeForces Problem Link:https://codeforces.com/problemset/problem/50/A  #############################################
#############################Code Generated By: Hasan Saleh ################################################
import math
a=input() 
m=int(a.split()[0]) 
n=int(a.split()[1]) 
print(math.floor((m*n)/2))
