###############Problem Link : https://codeforces.com/problemset/problem/4/A ##############################
###############Code Generated By : Hasan Saleh #############
w=input()
w=int(w)
if(w>2 and w<=100 and w%2 ==0 ):
    print("YES")
else:
    print("NO")
